apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-koden-meow-secret
                  key: mongodb-uri
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-session-secret
                  key: secret
            - name: PORT
              value: "9000"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ENV
              value: "production"
