apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meow-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.url }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meow-service
                port:
                  number: 3000
