apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongodb.username | b64enc }}
  mongo-root-password: {{ randAlphaNum 32 | b64enc }}