apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
