apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: {{ .Values.mongodb.name }}-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
