apiVersion: v1
kind: Service
metadata:
  name: meow-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: meow-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
