app:
  name: koden-app-meow
  image: killiankopp/meow:1.0
  replicas: 1
  port: 3000
  url: meow.koden.bzh
  db: mongodb://koden-mongodb-meow:27017/meow
  namespace: koden

mongodb:
  name: koden-mongodb-meow
  image: mongo:6
  port: 27017
  persistence:
    enabled: true
    size: 1Gi
